---
title: "NetworkConstruction"
output: html_document
date: "2023-12-07"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r Load data and packages}
#load packages
#install_infomap(target_folder = NULL, source = "binary")
#devtools::install_github('Ecological-Complexity-Lab/infomap_ecology_package', force=T)
library(tidyverse); library(scales);library(bipartite);library(ggpubr);library(igraph);library(metaforest);library(ggnetwork);library(viridis);library(MuMIn)

#load data
enviro_adj <- read.csv("~/Documents/Manuscripts/SAVA_Network/Data/Environmental_overlap_unipartite.csv")
contact_adj <- read.csv("~/Documents/Manuscripts/SAVA_Network/Data/Close_contact.csv")
name_undirected_man <- readRDS("~/Documents/Projects/SAVA_multilayer/everyone_name_undirected_M12.RDS")
name_undirectedvaillage_s <- readRDS("~/Documents/Projects/SAVA_multilayer/everyone_name_undirected_S123.RDS")
name_undirectedvaillage_a <- readRDS("~/Documents/Projects/SAVA_multilayer/everyone_name_undirected_A123.RDS")
house_dist <- read.csv("~/Documents/Projects/SAVA_multilayer/House_distance.csv")
metadata <- read.csv("~/Documents/Manuscripts/SAVA_Network/Data/Survey_Demographic_Health.csv")


```

```{r Edgelist Construction}
#Assign village
village <- metadata %>% select(social_netid, village) %>% rename("id1" = "social_netid") %>% distinct()

#Environmental network
enviro_adj2 <- enviro_adj %>% filter(network!="all", network!="village") %>% group_by(id1, id2, village) %>% summarise(weight=sum(weight))
enviro_adj2 <- enviro_adj2[!grepl("Z", enviro_adj2$id1),]
enviro_adj2 <- enviro_adj2[!grepl("Z", enviro_adj2$id2),]
envirovaillage_m_edge <- enviro_adj2 %>% filter(village =="M") %>% select(id1, id2, weight)
envirovaillage_s_edge <- enviro_adj2 %>% filter(village =="S") %>% select(id1, id2, weight)
envirovaillage_a_edge <- enviro_adj2 %>% filter(village =="A") %>% select(id1, id2, weight) 

#Close Contact network
contact_adj <- left_join(contact_adj, village, by="id1")
contact_adj2 <- contact_adj[!grepl("Z", contact_adj$id1),]
contact_adj2 <- contact_adj2[!grepl("Z", contact_adj2$id2),]
contactvaillage_m_edge <- contact_adj %>% filter(village =="M") %>% select(id1, id2, close_contact_edge) %>% rename("weight" = "close_contact_edge") %>% filter(weight!=0)
contactvaillage_s_edge <- contact_adj %>% filter(village =="S") %>% select(id1, id2, close_contact_edge) %>% rename("weight" = "close_contact_edge") %>% filter(weight!=0)
contactvaillage_a_edge <- contact_adj %>% filter(village =="A") %>% select(id1, id2, close_contact_edge) %>% rename("weight" = "close_contact_edge") %>% filter(weight!=0)

#Naming network

name_undirected_man2 <-name_undirected_man$n.named
name_undirectedvaillage_s2 <-name_undirectedvaillage_s$n.named
name_undirectedvaillage_a2 <-name_undirectedvaillage_a$n.named

namevaillage_m_edge <- igraph::as_data_frame(name_undirected_man2) %>% rename(id1 = from, id2 = to)
namevaillage_s_edge <- igraph::as_data_frame(name_undirectedvaillage_s2)%>% rename(id1 = from, id2 = to)
namevaillage_a_edge <- igraph::as_data_frame(name_undirectedvaillage_a2)%>% rename(id1 = from, id2 = to)

#Household distance network
house_dist <- house_dist[house_dist$dist!=0,]
house_dist$dist <- 1/house_dist$dist

distance_edges <- left_join(house_dist, village, by = "id1")%>% filter(dist !=0)
distancevaillage_m_edge <- distance_edges %>% filter(village=="M")
distancevaillage_a_edge <- distance_edges %>% filter(village=="A")
distancevaillage_s_edge <- distance_edges %>% filter(village=="S")


```

```{r Build Networks: M}
#Setup intra-layer edge lists
envirovaillage_m_edge <- envirovaillage_m_edge %>% rename(node.from =id1, node.to = id2)%>% mutate(layer.from =1, layer.to =1) %>% select(node.from, layer.from, node.to, layer.to, weight) %>% mutate(weight = rescale(weight,to = c(0.01,1)))

contactvaillage_m_edge <- contactvaillage_m_edge %>% rename(node.from =id1, node.to = id2)%>% mutate(layer.from =2, layer.to =2)%>% select(node.from, layer.from, node.to, layer.to, weight)%>% mutate(weight = rescale(weight,to = c(0.01,1)))

namevaillage_m_edge <- namevaillage_m_edge %>% rename(node.from =id1, node.to = id2)%>% mutate(layer.from =3, layer.to =3)%>% select(node.from, layer.from, node.to, layer.to, weight)%>% mutate(weight = rescale(weight,to = c(0.01,1)))


ggplot(data= envirovaillage_m_edge, aes(x = weight))+ geom_histogram()
ggplot(data= contactvaillage_m_edge, aes(x = weight))+ geom_histogram()
ggplot(data= namevaillage_m_edge, aes(x = weight))+ geom_histogram()

mean(envirovaillage_m_edge$weight)
mean(contactvaillage_m_edge$weight)
mean(namevaillage_m_edge$weight)
mean(c(envirovaillage_m_edge$weight, contactvaillage_m_edge$weight, namevaillage_m_edge$weight))

namevaillage_m_edge <- namevaillage_m_edge %>% filter(node.to %in% node.from)#filter out people named in different villages 

```

```{r Build Networks: S}
#Setup intra-layer edge lists
envirovaillage_s_edge <- envirovaillage_s_edge %>% rename(node.from =id1, node.to = id2)%>% mutate(layer.from =1, layer.to =1) %>% select(node.from, layer.from, node.to, layer.to, weight) %>% mutate(weight = rescale(weight,to = c(0.01,1)))
contactvaillage_s_edge <- contactvaillage_s_edge %>% rename(node.from =id1, node.to = id2)%>% mutate(layer.from =2, layer.to =2)%>% select(node.from, layer.from, node.to, layer.to, weight)%>% mutate(weight = rescale(weight,to = c(0.01,1)))
namevaillage_s_edge <- namevaillage_s_edge %>% rename(node.from =id1, node.to = id2)%>% mutate(layer.from =3, layer.to =3)%>% select(node.from, layer.from, node.to, layer.to, weight)%>% mutate(weight = rescale(weight,to = c(0.01,1)))

namevaillage_s_edge <- namevaillage_s_edge %>% filter(node.to %in% node.from)#filter out people named in different villages 



```

```{r Build Networks: A}
#Setup intra-layer edge lists
envirovaillage_a_edge <- envirovaillage_a_edge %>% rename(node.from =id1, node.to = id2)%>% mutate(layer.from =1, layer.to =1) %>% select(node.from, layer.from, node.to, layer.to, weight) %>% mutate(weight = rescale(weight,to = c(0.01,1)))
contactvaillage_a_edge <- contactvaillage_a_edge %>% rename(node.from =id1, node.to = id2)%>% mutate(layer.from =2, layer.to =2)%>% select(node.from, layer.from, node.to, layer.to, weight)%>% mutate(weight = rescale(weight,to = c(0.01,1)))
namevaillage_a_edge <- namevaillage_a_edge %>% rename(node.from =id1, node.to = id2)%>% mutate(layer.from =3, layer.to =3)%>% select(node.from, layer.from, node.to, layer.to, weight)%>% mutate(weight = rescale(weight,to = c(0.01,1)))

namevaillage_a_edge <- namevaillage_a_edge %>% filter(node.to %in% node.from)#filter out people named in different villages 

```

```{r Single-layer Centrality}
#GET SINGLE-LAYER GRAPHS
#M
envirovaillage_m_g <- graph_from_edgelist(as.matrix(envirovaillage_m_edge[,c(1,3)]), directed = FALSE)
namevaillage_m_g <- graph_from_edgelist(as.matrix(namevaillage_m_edge[,c(1,3)]), directed = FALSE)
contactvaillage_m_g <- graph_from_edgelist(as.matrix(contactvaillage_m_edge[,c(1,3)]), directed = FALSE)
distancevaillage_m_g <- graph_from_edgelist(as.matrix(distancevaillage_m_edge[,c(1,2)]), directed = FALSE)

envirovaillage_m_g<-simplify(envirovaillage_m_g, remove.multiple = FALSE, remove.loops = TRUE)
namevaillage_m_g<-simplify(namevaillage_m_g, remove.multiple = FALSE, remove.loops = TRUE)
contactvaillage_m_g<-simplify(contactvaillage_m_g, remove.multiple = FALSE, remove.loops = TRUE)
distancevaillage_m_g<-simplify(distancevaillage_m_g, remove.multiple = FALSE, remove.loops = TRUE)

E(envirovaillage_m_g)$weight <- envirovaillage_m_edge$weight
E(namevaillage_m_g)$weight <- namevaillage_m_edge$weight
E(contactvaillage_m_g)$weight <- contactvaillage_m_edge$weight
E(distancevaillage_m_g)$weight <- distancevaillage_m_edge$dist

#S
envirovaillage_s_g <- graph_from_edgelist(as.matrix(envirovaillage_s_edge[,c(1,3)]), directed = FALSE)
namevaillage_s_g <-graph_from_edgelist(as.matrix(namevaillage_s_edge[,c(1,3)]), directed = FALSE)
contactvaillage_s_g <- graph_from_edgelist(as.matrix(contactvaillage_s_edge[,c(1,3)]), directed = FALSE)
distancevaillage_s_g <- graph_from_edgelist(as.matrix(distancevaillage_s_edge[,c(1,2)]), directed = FALSE)

envirovaillage_s_g<-simplify(envirovaillage_s_g, remove.multiple = FALSE, remove.loops = TRUE)
namevaillage_s_g<-simplify(namevaillage_s_g, remove.multiple = FALSE, remove.loops = TRUE)
contactvaillage_s_g<-simplify(contactvaillage_s_g, remove.multiple = FALSE, remove.loops = TRUE)
distancevaillage_s_g<-simplify(distancevaillage_s_g, remove.multiple = FALSE, remove.loops = TRUE)

E(envirovaillage_s_g)$weight <- envirovaillage_s_edge$weight
E(namevaillage_s_g)$weight <- namevaillage_s_edge$weight
E(contactvaillage_s_g)$weight <- contactvaillage_s_edge$weight
E(distancevaillage_s_g)$weight <- distancevaillage_s_edge$dist

#A
envirovaillage_a_g <- graph_from_edgelist(as.matrix(envirovaillage_a_edge[,c(1,3)]), directed = FALSE)
namevaillage_a_g <- graph_from_edgelist(as.matrix(namevaillage_a_edge[,c(1,3)]), directed = FALSE)
contactvaillage_a_g <- graph_from_edgelist(as.matrix(contactvaillage_a_edge[,c(1,3)]), directed = FALSE)
distancevaillage_a_g <- graph_from_edgelist(as.matrix(distancevaillage_a_edge[,c(1,2)]), directed = FALSE)

E(envirovaillage_a_g)$weight <- envirovaillage_a_edge$weight
E(namevaillage_a_g)$weight <- namevaillage_a_edge$weight
E(contactvaillage_a_g)$weight <- contactvaillage_a_edge$weight
E(distancevaillage_a_g)$weight <- distancevaillage_a_edge$dist

envirovaillage_a_g<-simplify(envirovaillage_a_g, remove.multiple = FALSE, remove.loops = TRUE)
namevaillage_a_g<-simplify(namevaillage_a_g, remove.multiple = FALSE, remove.loops = TRUE)
contactvaillage_a_g<-simplify(contactvaillage_a_g, remove.multiple = FALSE, remove.loops = TRUE)
distancevaillage_a_g<-simplify(distancevaillage_a_g, remove.multiple = FALSE, remove.loops = TRUE)



#CALCULATE CENTRALITY
#Environmental networks
centrality_envirovaillage_m <- as.data.frame(page_rank(envirovaillage_m_g)$vector) 
centrality_envirovaillage_m$Node <- rownames(centrality_envirovaillage_m)
colnames(centrality_envirovaillage_m)[1] <- "PageRank"

centrality_envirovaillage_s <- as.data.frame(page_rank(envirovaillage_s_g)$vector) 
centrality_envirovaillage_s$Node <- rownames(centrality_envirovaillage_s)
colnames(centrality_envirovaillage_s)[1] <- "PageRank"

centrality_envirovaillage_a <- as.data.frame(page_rank(envirovaillage_a_g)$vector) 
centrality_envirovaillage_a$Node <- rownames(centrality_envirovaillage_a)
colnames(centrality_envirovaillage_a)[1] <- "PageRank"

#Close contact networks
centrality_contactvaillage_m <- as.data.frame(page_rank(contactvaillage_m_g)$vector) 
centrality_contactvaillage_m$Node <- rownames(centrality_contactvaillage_m)
colnames(centrality_contactvaillage_m)[1] <- "PageRank"

centrality_contactvaillage_s <- as.data.frame(page_rank(contactvaillage_s_g)$vector) 
centrality_contactvaillage_s$Node <- rownames(centrality_contactvaillage_s)
colnames(centrality_contactvaillage_s)[1] <- "PageRank"

centrality_contactvaillage_a <- as.data.frame(page_rank(contactvaillage_a_g)$vector) 
centrality_contactvaillage_a$Node <- rownames(centrality_contactvaillage_a)
colnames(centrality_contactvaillage_a)[1] <- "PageRank"

#Naming networks
centrality_namevaillage_m <- as.data.frame(page_rank(namevaillage_m_g)$vector) 
centrality_namevaillage_m$Node <- rownames(centrality_namevaillage_m)
colnames(centrality_namevaillage_m)[1] <- "PageRank"

centrality_namevaillage_s <- as.data.frame(page_rank(namevaillage_s_g)$vector) 
centrality_namevaillage_s$Node <- rownames(centrality_namevaillage_s)
colnames(centrality_namevaillage_s)[1] <- "PageRank"

centrality_namevaillage_a <- as.data.frame(page_rank(namevaillage_a_g)$vector) 
centrality_namevaillage_a$Node <- rownames(centrality_namevaillage_a)
colnames(centrality_namevaillage_a)[1] <- "PageRank"

#Distance networks
centrality_distancevaillage_m <- as.data.frame(page_rank(distancevaillage_m_g)$vector) 
centrality_distancevaillage_m$Node <- rownames(centrality_distancevaillage_m)
colnames(centrality_distancevaillage_m)[1] <- "PageRank"

centrality_distancevaillage_s <- as.data.frame(page_rank(distancevaillage_s_g)$vector) 
centrality_distancevaillage_s$Node <- rownames(centrality_distancevaillage_s)
colnames(centrality_distancevaillage_s)[1] <- "PageRank"

centrality_distancevaillage_a <- as.data.frame(page_rank(distancevaillage_a_g)$vector) 
centrality_distancevaillage_a$Node <- rownames(centrality_distancevaillage_a)
colnames(centrality_distancevaillage_a)[1] <- "PageRank"


centrality_namevaillage_m$Strength <- igraph::strength(namevaillage_m_g)
centrality_namevaillage_m$Betweenness <- igraph::betweenness(namevaillage_m_g, weights = 1/E(namevaillage_m_g)$weight, normalized = T)
centrality_namevaillage_m$Eigen <- log(igraph::eigen_centrality(namevaillage_m_g)$vector)

centrality_namevaillage_s$Strength <- igraph::strength(namevaillage_s_g)
centrality_namevaillage_s$Betweenness <- igraph::betweenness(namevaillage_s_g, weights =1/ E(namevaillage_s_g)$weight, normalized = T)
centrality_namevaillage_s$Eigen <- log(igraph::eigen_centrality(namevaillage_s_g)$vector)

centrality_namevaillage_a$Strength <- igraph::strength(namevaillage_a_g)
centrality_namevaillage_a$Betweenness <- igraph::betweenness(namevaillage_a_g, weights = 1/E(namevaillage_a_g)$weight, normalized = T)
centrality_namevaillage_a$Eigen <- log(igraph::eigen_centrality(namevaillage_a_g)$vector)


centrality_contactvaillage_m$Strength <- igraph::strength(contactvaillage_m_g)
centrality_contactvaillage_m$Betweenness <- igraph::betweenness(contactvaillage_m_g, weights = 1/E(contactvaillage_m_g)$weight, normalized = T)
centrality_contactvaillage_m$Eigen <- igraph::eigen_centrality(contactvaillage_m_g)$vector

centrality_contactvaillage_s$Strength <- igraph::strength(contactvaillage_s_g)
centrality_contactvaillage_s$Betweenness <- igraph::betweenness(contactvaillage_s_g, weights = 1/E(contactvaillage_s_g)$weight, normalized = T)
centrality_contactvaillage_s$Eigen <- igraph::eigen_centrality(contactvaillage_s_g)$vector

centrality_contactvaillage_a$Strength <- igraph::strength(contactvaillage_a_g)
centrality_contactvaillage_a$Betweenness <- igraph::betweenness(contactvaillage_a_g, weights = 1/E(contactvaillage_a_g)$weight, normalized = T)
centrality_contactvaillage_a$Eigen <- igraph::eigen_centrality(contactvaillage_a_g)$vector


centrality_envirovaillage_m$Strength <- igraph::strength(envirovaillage_m_g)
centrality_envirovaillage_m$Betweenness <- igraph::betweenness(envirovaillage_m_g, weights = 1/E(envirovaillage_m_g)$weight, normalized = T)
centrality_envirovaillage_m$Eigen <- igraph::eigen_centrality(envirovaillage_m_g)$vector

centrality_envirovaillage_s$Strength <- igraph::strength(envirovaillage_s_g)
centrality_envirovaillage_s$Betweenness <- igraph::betweenness(envirovaillage_s_g, weights = 1/E(envirovaillage_s_g)$weight, normalized = T)
centrality_envirovaillage_s$Eigen <- igraph::eigen_centrality(envirovaillage_s_g)$vector

centrality_envirovaillage_a$Strength <- igraph::strength(envirovaillage_a_g)
centrality_envirovaillage_a$Betweenness <- igraph::betweenness(envirovaillage_a_g, weights = 1/E(envirovaillage_a_g)$weight, normalized = T)
centrality_envirovaillage_a$Eigen <- igraph::eigen_centrality(envirovaillage_a_g)$vector


centrality_distancevaillage_m$Strength <- igraph::strength(distancevaillage_m_g)
centrality_distancevaillage_m$Betweenness <- igraph::betweenness(distancevaillage_m_g, weights = 1/E(distancevaillage_m_g)$weight, normalized = T)
centrality_distancevaillage_m$Eigen <- igraph::eigen_centrality(distancevaillage_m_g)$vector

centrality_distancevaillage_s$Strength <- igraph::strength(distancevaillage_s_g)
centrality_distancevaillage_s$Betweenness <- igraph::betweenness(distancevaillage_s_g, weights = 1/E(distancevaillage_s_g)$weight, normalized = T)
centrality_distancevaillage_s$Eigen <- igraph::eigen_centrality(distancevaillage_s_g)$vector

centrality_distancevaillage_a$Strength <- igraph::strength(distancevaillage_a_g)
centrality_distancevaillage_a$Betweenness <- igraph::betweenness(distancevaillage_a_g, weights = 1/E(distancevaillage_a_g)$weight, normalized = T)
centrality_distancevaillage_a$Eigen <- igraph::eigen_centrality(distancevaillage_a_g)$vector


```

```{r}

centrality_contactvaillage_m$Type <- "Contact"
centrality_namevaillage_m$Type <- "Name"
centrality_envirovaillage_m$Type <- "Enviro"
centrality_distancevaillage_m$Type <- "House"

contact_dfvaillage_m <- rbind(centrality_contactvaillage_m, centrality_namevaillage_m,centrality_envirovaillage_m,centrality_distancevaillage_m)
contact_dfvaillage_m$Village <- "M"

centrality_contactvaillage_a$Type <- "Contact"
centrality_namevaillage_a$Type <- "Name"
centrality_envirovaillage_a$Type <- "Enviro"
centrality_distancevaillage_a$Type <- "House"

contact_dfvaillage_a <- rbind(centrality_contactvaillage_a, centrality_namevaillage_a,centrality_envirovaillage_a,centrality_distancevaillage_a)
contact_dfvaillage_a$Village <- "A"

centrality_contactvaillage_s$Type <- "Contact"
centrality_namevaillage_s$Type <- "Name"
centrality_envirovaillage_s$Type <- "Enviro"
centrality_distancevaillage_s$Type <- "House"

contact_dfvaillage_s <- rbind(centrality_contactvaillage_s, centrality_namevaillage_s,centrality_envirovaillage_s,centrality_distancevaillage_s)
contact_dfvaillage_s$Village <- "S"

contact_df <- rbind(contact_dfvaillage_m, contact_dfvaillage_a, contact_dfvaillage_s)

colnames(contact_df) <- c( "PR", "Node","Stg", "Btwn", "Egn", "Type", "Village")

contact_df2 <-contact_df %>% pivot_wider(names_from = Type, values_from = c(PR, Stg, Btwn, Egn))

 
centrality_vars <- contact_df2[ , -c(1,2)]

write.csv(contact_df2, "contact_df2.csv")


```

```{r Generate market integration indices}

# wall construction
metadata$material_wall_index <- 0
metadata$material_wall_index[metadata$material_wall =="bamboo"] <- 0
metadata$material_wall_index[metadata$material_wall =="rafia"] <- 0
metadata$material_wall_index[metadata$material_wall =="ravenala"] <- 0
metadata$material_wall_index[metadata$material_wall =="mud"] <- 0
metadata$material_wall_index[metadata$material_wall =="compacted_earth"] <- 0
metadata$material_wall_index[metadata$material_wall =="wood_planks"] <- 1
metadata$material_wall_index[metadata$material_wall =="brick_unfired"] <- 2
metadata$material_wall_index[metadata$material_wall =="brick_fired"] <- 2
metadata$material_wall_index[metadata$material_wall =="metal_sheets"] <- 3
metadata$material_wall_index[metadata$material_wall =="cement"] <- 4

# roof construction
metadata$material_roof_index <- 0
metadata$material_roof_index[metadata$material_roof=="bamboo"] <- 0
metadata$material_roof_index[metadata$material_roof=="thatch"] <- 0
metadata$material_roof_index[metadata$material_roof=="metal_sheets"] <- 1
metadata$material_roof_index[metadata$material_roof=="cement"] <- 2

# floor construction
metadata$material_floor_index <- 0
metadata$material_floor_index[metadata$material_floor=="dirt"] <- 0
metadata$material_floor_index[metadata$material_floor=="bamboo"] <- 0
metadata$material_floor_index[metadata$material_floor=="rafia"] <- 0
metadata$material_floor_index[metadata$material_floor=="ravinala"] <- 0
metadata$material_floor_index[metadata$material_floor=="wood_planks"] <- 1
metadata$material_floor_index[metadata$material_floor=="cement"] <- 02

# household SOL index
metadata$house_sol <- metadata$material_wall_index + metadata$material_roof_index + metadata$material_floor_index

#################################
## Durable Commercial Goods Index
#################################

# change "Yes" responses to 1s
metadata$own_cellphone[metadata$own_cellphone=="Yes"] <- 1
metadata$own_cellphone[metadata$own_cellphone!=1] <- 0
metadata$own_cellphone <- as.numeric(metadata$own_cellphone)

metadata$own_tv[metadata$own_tv=="Yes"] <- 1
metadata$own_tv[metadata$own_tv!=1] <- 0
metadata$own_tv <- as.numeric(metadata$own_tv)

metadata$own_bicycle[metadata$own_bicycle=="Yes"] <- 1
metadata$own_bicycle[metadata$own_bicycle!=1] <- 0
metadata$own_bicycle <- as.numeric(metadata$own_bicycle)

metadata$own_refrigerator[metadata$own_refrigerator=="Yes"] <- 1
metadata$own_refrigerator[metadata$own_refrigerator!=1] <- 0
metadata$own_refrigerator <- as.numeric(metadata$own_refrigerator)

metadata$own_motorcycle[metadata$own_motorcycle=="Yes"] <- 1
metadata$own_motorcycle[metadata$own_motorcycle!=1] <- 0
metadata$own_motorcycle <- as.numeric(metadata$own_motorcycle)

metadata$own_computer[metadata$own_computer=="Yes"] <- 1
metadata$own_computer[metadata$own_computer!=1] <- 0
metadata$own_computer <- as.numeric(metadata$own_computer)

metadata$own_generator[metadata$own_generator=="Yes"] <- 1
metadata$own_generator[metadata$own_generator!=1] <- 0
metadata$own_generator <- as.numeric(metadata$own_generator)
  
metadata$commercial_goods <- metadata$own_cellphone + metadata$own_tv + metadata$own_bicycle + metadata$own_refrigerator + metadata$own_motorcycle + metadata$own_computer + metadata$own_generator


write.csv(metadata,"~/Documents/GitHub/human_animal_networks/gps_networks/metadata2.csv")

```

```{r Centrality and Demography}
#metadata$age <- scale(metadata$age)
#metadata$house_sol <- scale(metadata$house_sol)
#metadata$commercial_goods <- scale(metadata$commercial_goods)
#metadata$household_size <- scale(metadata$household_size)

metadata$village[metadata$village=="Ampandrana"] <- "A"

metadata$bmi <- (metadata$weight)/(metadata$height^2)
#metadata$bmi[metadata$bmi<18.5] <- 1
#metadata$bmi[metadata$bmi>1 & metadata$bmi<25] <- 2
#metadata$bmi[metadata$bmi>2 & metadata$bmi<30] <- 3
#metadata$bmi[metadata$bmi>30] <- 4

metadata$bmi <- scale(metadata$bmi)

metadata$meanDiastolic <- (metadata$diastolic1 +metadata$diastolic2 + metadata$diastolic3)/3
metadata$meanSystolic <- (metadata$systolic1 +metadata$systolic2 + metadata$systolic3)/3

metadata$bp <- metadata$meanSystolic / metadata$meanDiastolic
#metadata$bp[metadata$meanSystolic<90 | metadata$meanDiastolic <60] <- 0
metadata$bp[metadata$meanSystolic<120 & metadata$meanDiastolic <80 ] <- 1
metadata$bp[metadata$meanSystolic<=139 & metadata$meanDiastolic <=89 & metadata$bp!=1] <- 2
metadata$bp[metadata$meanSystolic>139 | metadata$meanDiastolic>89] <- 3
# Look into this https://www.cdc.gov/bloodpressure/about.htm#:~:text=Blood%20pressure%20is%20measured%20using,your%20heart%20rests%20between%20beats.
# low is just below 120
# make it ordinail 

#metadata$bp <- scale(metadata$bp)

# make education ordinal and add that 

# Look at networks in the different season 

#metadata$landsize_in_daba <- scale(metadata$landsize_in_daba)

metadata$school_level[metadata$school_level=="None"] <- 1
metadata$school_level[metadata$school_level=="Primary"] <- 2
metadata$school_level[metadata$school_level=="Secondary"] <- 3
metadata$school_level[metadata$school_level=="Higher"] <- 4

metadata$school_level <- as.numeric(metadata$school_level)

#metadata$school_level <- scale(metadata$school_level)

metadata <-metadata %>% mutate(livestock = farm_animals_cows +farm_animals_goats+farm_animals_pigs+farm_animals_sheep)
metadata$livestock <- scale(metadata$livestock)

cor.test(metadata$house_sol, metadata$commercial_goods)

cor.test(metadata$age, metadata$bp)

```

```{r Single-Layer Centrality Models Data Preparation}

metadata$Node <- metadata$social_netid

centrality_namevaillage_m2 <- left_join(centrality_namevaillage_m, metadata, by ="Node")
centrality_namevaillage_s2 <- left_join(centrality_namevaillage_s, metadata, by ="Node")
centrality_namevaillage_a2 <- left_join(centrality_namevaillage_a, metadata, by ="Node")

centrality_contactvaillage_m2 <- left_join(centrality_contactvaillage_m, metadata, by ="Node")
centrality_contactvaillage_s2 <- left_join(centrality_contactvaillage_s, metadata, by ="Node")
centrality_contactvaillage_a2 <- left_join(centrality_contactvaillage_a, metadata, by ="Node")

centrality_envirovaillage_m2 <- left_join(centrality_envirovaillage_m, metadata, by ="Node")
centrality_envirovaillage_s2 <- left_join(centrality_envirovaillage_s, metadata, by ="Node")
centrality_envirovaillage_a2 <- left_join(centrality_envirovaillage_a, metadata, by ="Node")

centrality_distancevaillage_m2 <- left_join(centrality_distancevaillage_m, metadata, by ="Node")
centrality_distancevaillage_s2 <- left_join(centrality_distancevaillage_s, metadata, by ="Node")
centrality_distancevaillage_a2 <- left_join(centrality_distancevaillage_a, metadata, by ="Node")


centrality_name_total2 <- rbind(centrality_namevaillage_m2, centrality_namevaillage_s2,centrality_namevaillage_a2) %>% dplyr::select(survey_date, Node, PageRank, gender,  age, house_sol, commercial_goods, village, school_level, bmi, landsize_in_daba,  livestock, season, household_size, Strength, Betweenness, Eigen) %>% drop_na() #getting rid of all NA values removed 77 individuals (~6% of all nodes)

centrality_name_total2$season <- as.factor(centrality_name_total2$season)

centrality_namevaillage_m_df <- centrality_name_total2[centrality_name_total2$village=="M",]
centrality_namevaillage_s_df <- centrality_name_total2[centrality_name_total2$village=="S",]
centrality_namevaillage_a_df <- centrality_name_total2[centrality_name_total2$village=="A",]

centrality_contact_total2 <- rbind(centrality_contactvaillage_m2, centrality_contactvaillage_s2,centrality_contactvaillage_a2) %>% select(survey_date,Node, PageRank, gender,  age, house_sol, commercial_goods, village, school_level, bmi, landsize_in_daba, livestock, season, household_size, Strength, Betweenness, Eigen) %>%drop_na()#getting rid of all NA values removed 36 individuals (~4% of all nodes)

centrality_contact_total2$season <- as.factor(centrality_contact_total2$season)


centrality_contactvaillage_m_df <- centrality_contact_total2[centrality_contact_total2$village=="M",]
centrality_contactvaillage_s_df <- centrality_contact_total2[centrality_contact_total2$village=="S",]
centrality_contactvaillage_a_df <- centrality_contact_total2[centrality_contact_total2$village=="A",]

centrality_enviro_total2 <- rbind(centrality_envirovaillage_m2, centrality_envirovaillage_s2,centrality_envirovaillage_a2) %>% select(survey_date,Node, PageRank, gender,  age, house_sol, commercial_goods, village, school_level, bmi, landsize_in_daba, livestock, season, household_size, Strength, Betweenness, Eigen) %>%drop_na()#getting rid of all NA values removed 42 individuals (~5% of all nodes)



centrality_envirovaillage_m_df <- centrality_enviro_total2[centrality_enviro_total2$village=="M",]
centrality_envirovaillage_s_df <- centrality_enviro_total2[centrality_enviro_total2$village=="S",]
centrality_envirovaillage_a_df <- centrality_enviro_total2[centrality_enviro_total2$village=="A",]


centrality_enviro_total2$season <- as.factor(centrality_enviro_total2$season)

centrality_distance_total2 <- rbind(centrality_distancevaillage_m2, centrality_distancevaillage_s2,centrality_distancevaillage_a2) %>% select(survey_date,Node, PageRank, gender,  age, house_sol, commercial_goods, village, school_level, bmi, landsize_in_daba, livestock, season, household_size, Strength, Betweenness, Eigen) %>%drop_na()#getting rid of all NA values removed 67 individuals (~5% of all nodes)

centrality_distance_total2$season <- as.factor(centrality_distance_total2$season)

centrality_distancevaillage_m_df <- centrality_distance_total2[centrality_distance_total2$village=="M",]
centrality_distancevaillage_s_df <- centrality_distance_total2[centrality_distance_total2$village=="S",]
centrality_distancevaillage_a_df <- centrality_distance_total2[centrality_distance_total2$village=="A",]

```

```{r Regression(Not meta-analysis): Naming}

centrality_name_total2$survey_date <- as.Date(centrality_name_total2$survey_date)

centrality_name_total2 <- centrality_name_total2 %>%
  mutate(survey_date = as.Date(survey_date)) %>%      
  mutate(
    date_index = dense_rank(survey_date)       
  ) %>%
  ungroup()

centrality_name_total2$Betweenness <- scale(centrality_name_total2$Betweenness)
centrality_name_total2$Eigen <- scale(centrality_name_total2$Eigen)
centrality_name_total2$PageRank <- scale(centrality_name_total2$PageRank)
centrality_name_total2$Strength <- scale(centrality_name_total2$Strength)


centrality_name_total3 <- centrality_name_total2 %>% pivot_longer(names_to = "centrality", values_to = "value", cols = c(Betweenness, Eigen, PageRank, Strength))

  
  centrality_name_total3$age <- scale(centrality_name_total3$age)
  centrality_name_total3$house_sol <- scale(centrality_name_total3$house_sol)
  centrality_name_total3$commercial_goods <- scale(centrality_name_total3$commercial_goods)
  centrality_name_total3$school_level <- scale(centrality_name_total3$school_level)
  centrality_name_total3$bmi <- scale(centrality_name_total3$bmi)
  centrality_name_total3$landsize_in_daba <- scale(centrality_name_total3$landsize_in_daba)
  centrality_name_total3$livestock <- scale(centrality_name_total3$livestock)
  centrality_name_total3$household_size <- scale(centrality_name_total3$household_size)
  centrality_name_total3$date_index <- scale(centrality_name_total3$date_index)
  
  centrality_name_model <- lmer(value ~gender + age + house_sol + commercial_goods+ school_level+bmi+landsize_in_daba +livestock + household_size + season + village +centrality +date_index +(1|Node), data= centrality_name_total3)

  
  options(na.action = "na.fail")
  name_model_selection <- MuMIn::dredge(centrality_name_model)
  options(na.action = "na.omit")
  
  name_model_average <- summary(model.avg(  name_model_selection))
  
 name_model_average_coef <- as.data.frame(name_model_average$coefmat.full)
 name_model_average_coef$Variable <- rownames(name_model_average_coef)
 
 
 importance <- as.data.frame(sw(model.avg(name_model_selection)))
  colnames(importance)[1] <- "Importance"
  importance$Variable <- rownames(importance)
  importance$Variable[importance$Variable=="gender"] <- "genderMale"
 
 name_model_average_coef <- left_join(name_model_average_coef, importance, by = "Variable")
 
 name_model_average_coef$Importance[name_model_average_coef$Variable=="season2"] <-  importance$Importance[importance$Variable=="season"]
 
  name_model_average_coef$Importance[name_model_average_coef$Variable=="season3"] <-  importance$Importance[importance$Variable=="season"]
  
  name_model_average_coef$Importance[name_model_average_coef$Variable=="villageM"] <-  importance$Importance[importance$Variable=="village"]
   
 name_model_average_coef$Importance[name_model_average_coef$Variable=="villageS"] <-  importance$Importance[importance$Variable=="village"]
     
  name_model_average_coef$Importance[name_model_average_coef$Variable=="centralityEigen"|name_model_average_coef$Variable=="centralityStrength"|name_model_average_coef$Variable=="centralityPageRank"] <-  importance$Importance[importance$Variable=="centrality"]
  
 
 name_model_average_coef$lower_ci <-  name_model_average_coef$Estimate - 1.96 *  name_model_average_coef$`Std. Error`
 
 name_model_average_coef$upper_ci <-  name_model_average_coef$Estimate + 1.96 *  name_model_average_coef$`Std. Error`

 name_model_average_coef$lower_ci_90 <-  name_model_average_coef$Estimate - 1.644854*  name_model_average_coef$`Std. Error`
 
 name_model_average_coef$upper_ci_90 <-  name_model_average_coef$Estimate +1.644854*  name_model_average_coef$`Std. Error`

 
  name_model_average_coef$Variable <- c("Intercept","Date Index", "Season[2]", "Season[3]", "Village[M]", "Village[S]", "Gender[Man]","Livestock", "BMI","Education","Goods","Land Size","Age", "Household Size", "House Material" ,"Centrality[Eigenvector]", "Centrality[PageRank]", "Centrality[Strength]")

  name_model_average_coef$Variable <- factor(name_model_average_coef$Variable, levels = c("Livestock", "Land Size", "House Material", "Household Size", "Goods", "Education","BMI", "Age", "Gender[Man]", "Centrality[Eigenvector]", "Centrality[PageRank]", "Centrality[Strength]", "Season[2]", "Season[3]", "Village[M]", "Village[S]", "Date Index", "Intercept"))
  
  name_model_average_coef2 <- name_model_average_coef%>% filter(Variable!="Centrality[Eigenvector]", 
                                                               Variable!="Centrality[PageRank]",
                                                               Variable!="Centrality[Strength]",
                                                               Variable!="Season[2]",
                                                               Variable!="Season[3]",
                                                               Variable!="Village[M]",
                                                               Variable!="Village[S]",
                                                               Variable !="Date Index",
                                                               Variable!= "Intercept")
 
name_plot3 <- ggplot(data=name_model_average_coef2, aes(x = Variable , y= Estimate, color = Importance))+
  geom_hline(aes(yintercept=0), linetype="dashed")+
  geom_linerange(aes(ymin = lower_ci, ymax = upper_ci), position = position_dodge(1), linewidth=0.3) +
geom_linerange(aes(ymin = lower_ci_90, ymax = upper_ci_90), position = position_dodge(1), linewidth=1) +
 geom_point(aes(x = Variable, y= Estimate), position = position_dodge(1), size=2)+
  xlab("")+
  ylab("Standardized Effect\non Centrality")+
  ggtitle("Social")+
  coord_flip()+
  theme_classic()+
  scale_color_viridis_c(
    direction = -1, limits = c(0,1.01))+
  theme(
    plot.title = element_text(size = 16, face = "bold"),
    axis.title = element_text(size = 14),
    axis.text = element_text(size = 12),
    legend.title = element_text(size = 13),
    legend.text = element_text(size = 11)
  )

name_model_average_coef3 <- name_model_average_coef %>%
  filter(Variable %in% c("Centrality[Eigenvector]",
                         "Centrality[PageRank]",
                         "Centrality[Strength]",
                         "Season[2]",
                         "Season[3]",
                         "Village[M]",
                         "Village[S]",
                         "Date Index"))
 
name_plot4 <- ggplot(data=name_model_average_coef3, aes(x = Variable , y= Estimate, color = Importance))+
  geom_hline(aes(yintercept=0), linetype="dashed")+
  geom_linerange(aes(ymin = lower_ci, ymax = upper_ci), position = position_dodge(1), linewidth=0.3) +
geom_linerange(aes(ymin = lower_ci_90, ymax = upper_ci_90), position = position_dodge(1), linewidth=1) +
 geom_point(aes(x = Variable, y= Estimate), position = position_dodge(1), size=2)+
  xlab("")+
  ylab("Standardized Effect\non Centrality")+
  ggtitle("Social")+
  coord_flip()+
  theme_classic()+
  scale_color_viridis_c(
    direction = -1, limits = c(0,1.01))+
  theme(
    plot.title = element_text(size = 16, face = "bold"),
    axis.title = element_text(size = 14),
    axis.text = element_text(size = 12),
    legend.title = element_text(size = 13),
    legend.text = element_text(size = 11)
  )



```

```{r Regression(Not meta-analysis): Distance}

centrality_distance_total2$survey_date <- as.Date(centrality_distance_total2$survey_date)

centrality_distance_total2 <- centrality_distance_total2 %>%
  mutate(survey_date = as.Date(survey_date)) %>%  
  mutate(
    date_index = dense_rank(survey_date)             
  ) %>%
  ungroup()


centrality_distance_total2$Betweenness <- scale(centrality_distance_total2$Betweenness)
centrality_distance_total2$Eigen <- scale(centrality_distance_total2$Eigen)
centrality_distance_total2$PageRank <- scale(centrality_distance_total2$PageRank)
centrality_distance_total2$Strength <- scale(centrality_distance_total2$Strength)

centrality_distance_total3 <- centrality_distance_total2 %>% pivot_longer(names_to = "centrality", values_to = "value", cols = c(Betweenness, Eigen, PageRank, Strength))


  centrality_distance_total3$age <- scale(centrality_distance_total3$age)
  centrality_distance_total3$house_sol <- scale(centrality_distance_total3$house_sol)
  centrality_distance_total3$commercial_goods <- scale(centrality_distance_total3$commercial_goods)
  centrality_distance_total3$school_level <- scale(centrality_distance_total3$school_level)
  centrality_distance_total3$bmi <- scale(centrality_distance_total3$bmi)
  centrality_distance_total3$landsize_in_daba <- scale(centrality_distance_total3$landsize_in_daba)
  centrality_distance_total3$livestock <- scale(centrality_distance_total3$livestock)
  centrality_distance_total3$household_size <- scale(centrality_distance_total3$household_size)
   centrality_distance_total3$date_index <- scale( centrality_distance_total3$date_index)

  
  centrality_distance_model <- lmer(value ~gender + age + house_sol + commercial_goods+ school_level+bmi+landsize_in_daba +livestock + household_size + season + village+ centrality+ date_index+(1|Node)
                           , data= centrality_distance_total3)

  
  options(na.action = "na.fail")
  distance_model_selection <- dredge(centrality_distance_model)
  options(na.action = "na.omit")
  
  distance_model_average <- summary(model.avg(distance_model_selection))
  
 distance_model_average_coef <- as.data.frame(distance_model_average$coefmat.full)
 distance_model_average_coef$Variable <- rownames(distance_model_average_coef)
 
 
  
 importance <- as.data.frame(sw(model.avg(distance_model_selection)))
  colnames(importance)[1] <- "Importance"
  importance$Variable <- rownames(importance)
  importance$Variable[importance$Variable=="gender"] <- "genderMale"
 
 distance_model_average_coef <- left_join(distance_model_average_coef, importance, by = "Variable")
 
 distance_model_average_coef$Importance[distance_model_average_coef$Variable=="season2"] <-  importance$Importance[importance$Variable=="season"]
 
  distance_model_average_coef$Importance[distance_model_average_coef$Variable=="season3"] <-  importance$Importance[importance$Variable=="season"]
  
  distance_model_average_coef$Importance[distance_model_average_coef$Variable=="villageM"] <-  importance$Importance[importance$Variable=="village"]
   
 distance_model_average_coef$Importance[distance_model_average_coef$Variable=="villageS"] <-  importance$Importance[importance$Variable=="village"]
     
  distance_model_average_coef$Importance[distance_model_average_coef$Variable=="centralityEigen"|distance_model_average_coef$Variable=="centralityStrength"|distance_model_average_coef$Variable=="centralityPageRank"] <-  importance$Importance[importance$Variable=="centrality"]
  
 
 distance_model_average_coef$lower_ci <-  distance_model_average_coef$Estimate - 1.96 *  distance_model_average_coef$`Std. Error`
 
 distance_model_average_coef$upper_ci <-  distance_model_average_coef$Estimate + 1.96 *  distance_model_average_coef$`Std. Error`

 distance_model_average_coef$lower_ci_90 <-  distance_model_average_coef$Estimate - 1.644854*  distance_model_average_coef$`Std. Error`
 
 distance_model_average_coef$upper_ci_90 <-  distance_model_average_coef$Estimate +1.644854*  distance_model_average_coef$`Std. Error`

 
 
  distance_model_average_coef$Variable <- c("Intercept", "Date Index", "Season[2]", "Season[3]","Village[M]", "Village[S]","Goods", "Land Size", "Age", "House Material", "Household Size", "Gender[Man]", "Livestock","BMI", "Education","Centrality[Eigenvector]", "Centrality[PageRank]", "Centrality[Strength]" )

  distance_model_average_coef$Variable <- factor(distance_model_average_coef$Variable, levels = c("Livestock", "Land Size", "House Material", "Household Size", "Goods", "Education","BMI", "Age", "Gender[Man]", "Centrality[Eigenvector]", "Centrality[PageRank]", "Centrality[Strength]", "Season[2]", "Season[3]", "Village[M]", "Village[S]", "Date Index", "Intercept"))
  
distance_model_average_coef2 <-distance_model_average_coef%>% filter(Variable!="Centrality[Eigenvector]", 
                                                               Variable!="Centrality[PageRank]",
                                                               Variable!="Centrality[Strength]",
                                                               Variable!="Season[2]",
                                                               Variable!="Season[3]",
                                                               Variable!="Village[M]",
                                                               Variable!="Village[S]",
                                                               Variable!="Date Index",
                                                               Variable!= "Intercept")
 
distance_plot3 <- ggplot(data=distance_model_average_coef2, aes(x = Variable , y= Estimate, color = Importance))+
  geom_hline(aes(yintercept=0), linetype="dashed")+
  geom_linerange(aes(ymin = lower_ci, ymax = upper_ci), position = position_dodge(1), linewidth=0.3) +
geom_linerange(aes(ymin = lower_ci_90, ymax = upper_ci_90), position = position_dodge(1), linewidth=1) +
 geom_point(aes(x = Variable, y= Estimate), position = position_dodge(1), size=2)+
  xlab("")+
  ylab("Standardized Effect\non Centrality")+
  ggtitle("Household")+
  coord_flip()+
  theme_classic()+
  scale_color_viridis_c(
    direction = -1, limits = c(0,1.01))+
  theme(
    plot.title = element_text(size = 16, face = "bold"),
    axis.title = element_text(size = 14),
    axis.text = element_text(size = 12),
    legend.title = element_text(size = 13),
    legend.text = element_text(size = 11)
  )

distance_model_average_coef3 <- distance_model_average_coef %>%
  filter(Variable %in% c("Centrality[Eigenvector]",
                         "Centrality[PageRank]",
                         "Centrality[Strength]",
                         "Season[2]",
                         "Season[3]",
                         "Village[M]",
                         "Village[S]",
                         "Date Index"))

distance_plot4 <- ggplot(data=distance_model_average_coef3, aes(x = Variable , y= Estimate, color = Importance))+
  geom_hline(aes(yintercept=0), linetype="dashed")+
  geom_linerange(aes(ymin = lower_ci, ymax = upper_ci), position = position_dodge(1), linewidth=0.3) +
geom_linerange(aes(ymin = lower_ci_90, ymax = upper_ci_90), position = position_dodge(1), linewidth=1) +
 geom_point(aes(x = Variable, y= Estimate), position = position_dodge(1), size=2)+
  xlab("")+
  ylab("Standardized Effect\non Centrality")+
  ggtitle("Household")+
  coord_flip()+
  theme_classic()+
  scale_color_viridis_c(
    direction = -1, limits = c(0,1.01))+
  theme(
    plot.title = element_text(size = 16, face = "bold"),
    axis.title = element_text(size = 14),
    axis.text = element_text(size = 12),
    legend.title = element_text(size = 13),
    legend.text = element_text(size = 11)
  )

```

```{r Regression(Not meta-analysis): Contact}

centrality_contact_total2$survey_date <- as.Date(centrality_contact_total2$survey_date)

centrality_contact_total2 <- centrality_contact_total2 %>%
  mutate(survey_date = as.Date(survey_date)) %>%     
  mutate(
    date_index = dense_rank(survey_date)         
  ) %>%
  ungroup()

centrality_contact_total2$Betweenness <- scale(centrality_contact_total2$Betweenness)
centrality_contact_total2$Eigen <- scale(centrality_contact_total2$Eigen)
centrality_contact_total2$PageRank <- scale(centrality_contact_total2$PageRank)
centrality_contact_total2$Strength <- scale(centrality_contact_total2$Strength)


centrality_contact_total3 <- centrality_contact_total2 %>% pivot_longer(names_to = "centrality", values_to = "value", cols = c(Betweenness, Eigen, PageRank, Strength))

  
  centrality_contact_total3$age <- scale(centrality_contact_total3$age)
  centrality_contact_total3$house_sol <- scale(centrality_contact_total3$house_sol)
  centrality_contact_total3$commercial_goods <- scale(centrality_contact_total3$commercial_goods)
  centrality_contact_total3$school_level <- scale(centrality_contact_total3$school_level)
  centrality_contact_total3$bmi <- scale(centrality_contact_total3$bmi)
  centrality_contact_total3$landsize_in_daba <- scale(centrality_contact_total3$landsize_in_daba)
  centrality_contact_total3$livestock <- scale(centrality_contact_total3$livestock)
  centrality_contact_total3$household_size <- scale(centrality_contact_total3$household_size)
  centrality_contact_total3$date_index <- scale(centrality_contact_total3$date_index)
  
  centrality_contact_model <- lmer(value ~gender + age + house_sol + commercial_goods+ school_level+bmi+landsize_in_daba +livestock + household_size +season+ village +centrality+date_index +(1|Node) , data= centrality_contact_total3)

  
  options(na.action = "na.fail")
  contact_model_selection <- dredge(centrality_contact_model)
  options(na.action = "na.omit")
  
  contact_model_average <- summary(model.avg(contact_model_selection))
  

 contact_model_average_coef <- as.data.frame(contact_model_average$coefmat.full)
 contact_model_average_coef$Variable <- rownames(contact_model_average_coef)
 
  importance <- as.data.frame(sw(model.avg(contact_model_selection)))
  colnames(importance)[1] <- "Importance"
  importance$Variable <- rownames(importance)
  importance$Variable[importance$Variable=="gender"] <- "genderMale"
 
 contact_model_average_coef <- left_join(contact_model_average_coef, importance, by = "Variable")
 
 contact_model_average_coef$Importance[contact_model_average_coef$Variable=="season2"] <-  importance$Importance[importance$Variable=="season"]
 
  contact_model_average_coef$Importance[contact_model_average_coef$Variable=="season3"] <-  importance$Importance[importance$Variable=="season"]
  
   contact_model_average_coef$Importance[contact_model_average_coef$Variable=="villageM"] <-  importance$Importance[importance$Variable=="village"]
   
     contact_model_average_coef$Importance[contact_model_average_coef$Variable=="villageS"] <-  importance$Importance[importance$Variable=="village"]
     
      contact_model_average_coef$Importance[contact_model_average_coef$Variable=="centralityEigen"|contact_model_average_coef$Variable=="centralityStrength"|contact_model_average_coef$Variable=="centralityPageRank"] <-  importance$Importance[importance$Variable=="centrality"]
 
 contact_model_average_coef$lower_ci <-  contact_model_average_coef$Estimate - 1.96 *  contact_model_average_coef$`Std. Error`
 
 contact_model_average_coef$upper_ci <-  contact_model_average_coef$Estimate + 1.96 *  contact_model_average_coef$`Std. Error`

 contact_model_average_coef$lower_ci_90 <-  contact_model_average_coef$Estimate - 1.644854*  contact_model_average_coef$`Std. Error`
 
 contact_model_average_coef$upper_ci_90 <-  contact_model_average_coef$Estimate +1.644854*  contact_model_average_coef$`Std. Error`

  contact_model_average_coef$Variable <- c("Intercept", "Date Index", "House Material","Season[2]", "Season[3]","Village[M]", "Village[S]",  "Age", "Gender[Man]", "Land Size", "Goods", "BMI", "Household Size", "Livestock", "Education","Centrality[Eigenvector]", "Centrality[PageRank]", "Centrality[Strength]")

  contact_model_average_coef$Variable <- factor(contact_model_average_coef$Variable, levels = c("Livestock", "Land Size", "House Material", "Household Size", "Goods", "Education","BMI", "Age", "Gender[Man]", "Centrality[Eigenvector]", "Centrality[PageRank]", "Centrality[Strength]", "Season[2]", "Season[3]", "Village[M]", "Village[S]", "Date Index", "Intercept"))
  
contact_model_average_coef2 <- contact_model_average_coef%>% filter(Variable!="Centrality[Eigenvector]", 
                                                               Variable!="Centrality[PageRank]",
                                                               Variable!="Centrality[Strength]",
                                                               Variable!="Season[2]",
                                                               Variable!="Season[3]",
                                                               Variable!="Village[M]",
                                                               Variable!="Village[S]",
                                                               Variable!="Date Index",
                                                               Variable!= "Intercept")
 
contact_plot3 <- ggplot(data=contact_model_average_coef2, aes(x = Variable , y= Estimate, color=Importance))+
  geom_hline(aes(yintercept=0), linetype="dashed")+
  geom_linerange(aes(ymin = lower_ci, ymax = upper_ci), position = position_dodge(1), linewidth=0.3) +
geom_linerange(aes(ymin = lower_ci_90, ymax = upper_ci_90), position = position_dodge(1), linewidth=1) +
 geom_point(aes(x = Variable, y= Estimate), position = position_dodge(1), size=2)+
  xlab("")+
  ylab("Standardized Effect\non Centrality")+
  ggtitle("Close Contact")+
  coord_flip()+
  theme_classic()+
  scale_color_viridis_c(
    direction = -1, limits = c(0,1.01))+
  theme(
    plot.title = element_text(size = 16, face = "bold"),
    axis.title = element_text(size = 14),
    axis.text = element_text(size = 12),
    legend.title = element_text(size = 13),
    legend.text = element_text(size = 11)
  )

contact_model_average_coef3 <- contact_model_average_coef %>%
  filter(Variable %in% c("Centrality[Eigenvector]",
                         "Centrality[PageRank]",
                         "Centrality[Strength]",
                         "Season[2]",
                         "Season[3]",
                         "Village[M]",
                         "Village[S]",
                         "Date Index"))


contact_plot4 <- ggplot(data=contact_model_average_coef3, aes(x = Variable , y= Estimate, color=Importance))+
  geom_hline(aes(yintercept=0), linetype="dashed")+
  geom_linerange(aes(ymin = lower_ci, ymax = upper_ci), position = position_dodge(1), linewidth=0.3) +
geom_linerange(aes(ymin = lower_ci_90, ymax = upper_ci_90), position = position_dodge(1), linewidth=1) +
 geom_point(aes(x = Variable, y= Estimate), position = position_dodge(1), size=2)+
  xlab("")+
  ylab("Standardized Effect\non Centrality")+
  ggtitle("Close Contact")+
  coord_flip()+
  theme_classic()+
  scale_color_viridis_c(
    direction = -1, limits = c(0,1.01))+
  theme(
    plot.title = element_text(size = 16, face = "bold"),
    axis.title = element_text(size = 14),
    axis.text = element_text(size = 12),
    legend.title = element_text(size = 13),
    legend.text = element_text(size = 11)
  )

```

```{r Regression(Not meta-analysis): Enviro}

centrality_enviro_total2$survey_date <- as.Date(centrality_enviro_total2$survey_date)

centrality_enviro_total2 <- centrality_enviro_total2 %>%
  mutate(survey_date = as.Date(survey_date)) %>%      # ensure Date format
  mutate(
    date_index = dense_rank(survey_date)              # each unique date gets next integer
  ) %>%
  ungroup()


centrality_enviro_total2$Betweenness <- scale(centrality_enviro_total2$Betweenness)
centrality_enviro_total2$Eigen <- scale(centrality_enviro_total2$Eigen)
centrality_enviro_total2$PageRank <- scale(centrality_enviro_total2$PageRank)
centrality_enviro_total2$Strength <- scale(centrality_enviro_total2$Strength)

centrality_enviro_total3 <- centrality_enviro_total2 %>% pivot_longer(names_to = "centrality", values_to = "value", cols = c(Betweenness, Eigen, PageRank, Strength))
  
  centrality_enviro_total3$age <- scale(centrality_enviro_total3$age)
  centrality_enviro_total3$house_sol <- scale(centrality_enviro_total3$house_sol)
  centrality_enviro_total3$commercial_goods <- scale(centrality_enviro_total3$commercial_goods)
  centrality_enviro_total3$school_level <- scale(centrality_enviro_total3$school_level)
  centrality_enviro_total3$bmi <- scale(centrality_enviro_total3$bmi)
  centrality_enviro_total3$landsize_in_daba <- scale(centrality_enviro_total3$landsize_in_daba)
  centrality_enviro_total3$livestock <- scale(centrality_enviro_total3$livestock)
  centrality_enviro_total3$household_size <- scale(centrality_enviro_total3$household_size)
  centrality_enviro_total3$date_index <- scale(centrality_enviro_total3$date_index)
  
  centrality_enviro_model <- lmer(value ~gender + age + house_sol + commercial_goods+ school_level+bmi+landsize_in_daba +livestock + household_size + season + village +centrality+date_index + (1|Node)
                           , data= centrality_enviro_total3)
  
  options(na.action = "na.fail")
  enviro_model_selection <- dredge(centrality_enviro_model)
  options(na.action = "na.omit")
  
  enviro_model_average <- summary(model.avg(enviro_model_selection))
  
 enviro_model_average_coef <- as.data.frame(enviro_model_average$coefmat.full)
 enviro_model_average_coef$Variable <- rownames(enviro_model_average_coef)
 
 importance <- as.data.frame(sw(model.avg(enviro_model_selection)))
  colnames(importance)[1] <- "Importance"
  importance$Variable <- rownames(importance)
  importance$Variable[importance$Variable=="gender"] <- "genderMale"
 
 enviro_model_average_coef <- left_join(enviro_model_average_coef, importance, by = "Variable")
 
 enviro_model_average_coef$Importance[enviro_model_average_coef$Variable=="season2"] <-  importance$Importance[importance$Variable=="season"]
 
  enviro_model_average_coef$Importance[enviro_model_average_coef$Variable=="season3"] <-  importance$Importance[importance$Variable=="season"]
  
   enviro_model_average_coef$Importance[enviro_model_average_coef$Variable=="villageM"] <-  importance$Importance[importance$Variable=="village"]
   
     enviro_model_average_coef$Importance[enviro_model_average_coef$Variable=="villageS"] <-  importance$Importance[importance$Variable=="village"]
     
  enviro_model_average_coef$Importance[enviro_model_average_coef$Variable=="centralityEigen"|enviro_model_average_coef$Variable=="centralityStrength"|enviro_model_average_coef$Variable=="centralityPageRank"] <-  importance$Importance[importance$Variable=="centrality"]
     
 
 enviro_model_average_coef$lower_ci <-  enviro_model_average_coef$Estimate - 1.96 *  enviro_model_average_coef$`Std. Error`
 
 enviro_model_average_coef$upper_ci <-  enviro_model_average_coef$Estimate + 1.96 *  enviro_model_average_coef$`Std. Error`

 enviro_model_average_coef$lower_ci_90 <-  enviro_model_average_coef$Estimate - 1.644854*  enviro_model_average_coef$`Std. Error`
 
 enviro_model_average_coef$upper_ci_90 <-  enviro_model_average_coef$Estimate +1.644854*  enviro_model_average_coef$`Std. Error`

  enviro_model_average_coef$Variable <- c("Intercept","Date Index", "Gender[Man]","Season[2]", "Season[3]","Village[M]", "Village[S]", "House Material","Goods", "Land Size", "Age", "Education",  "BMI","Household Size", "Livestock", "Centrality[Eigenvector]", "Centrality[PageRank]", "Centrality[Strength]")

  enviro_model_average_coef$Variable <- factor(enviro_model_average_coef$Variable, levels =  c("Livestock", "Land Size", "House Material", "Household Size", "Goods", "Education","BMI", "Age", "Gender[Man]", "Centrality[Eigenvector]", "Centrality[PageRank]", "Centrality[Strength]", "Season[2]", "Season[3]", "Village[M]", "Village[S]","Date Index", "Intercept"))
  
enviro_model_average_coef2 <- enviro_model_average_coef%>% filter(Variable!="Centrality[Eigenvector]", 
                                                               Variable!="Centrality[PageRank]",
                                                               Variable!="Centrality[Strength]",
                                                               Variable!="Season[2]",
                                                               Variable!="Season[3]",
                                                               Variable!="Village[M]",
                                                               Variable!="Village[S]",
                                                               Variable !="Date Index",
                                                               Variable!= "Intercept")
 
enviro_plot3 <- ggplot(data=enviro_model_average_coef2, aes(x = Variable , y= Estimate, color =Importance))+
  geom_hline(aes(yintercept=0), linetype="dashed")+
  geom_linerange(aes(ymin = lower_ci, ymax = upper_ci), position = position_dodge(1), linewidth=0.3) +
geom_linerange(aes(ymin = lower_ci_90, ymax = upper_ci_90), position = position_dodge(1), linewidth=1) +
 geom_point(aes(x = Variable, y= Estimate), position = position_dodge(1), size=2)+
  xlab("")+
  ylab("Standardized Effect\non Centrality")+
  ggtitle("Environmental")+
  coord_flip()+
  theme_classic()+
  scale_color_viridis_c(
    direction = -1, limits = c(0,1.01))+
  theme(
    plot.title = element_text(size = 16, face = "bold"),
    axis.title = element_text(size = 14),
    axis.text = element_text(size = 12),
    legend.title = element_text(size = 13),
    legend.text = element_text(size = 11)
  )


enviro_model_average_coef3 <- enviro_model_average_coef %>%
  filter(Variable %in% c("Centrality[Eigenvector]",
                         "Centrality[PageRank]",
                         "Centrality[Strength]",
                         "Season[2]",
                         "Season[3]",
                         "Village[M]",
                         "Village[S]",
                         "Date Index"))


enviro_plot4 <- ggplot(data=enviro_model_average_coef3, aes(x = Variable , y= Estimate, color =Importance))+
  geom_hline(aes(yintercept=0), linetype="dashed")+
  geom_linerange(aes(ymin = lower_ci, ymax = upper_ci), position = position_dodge(1), linewidth=0.3) +
geom_linerange(aes(ymin = lower_ci_90, ymax = upper_ci_90), position = position_dodge(1), linewidth=1) +
 geom_point(aes(x = Variable, y= Estimate), position = position_dodge(1), size=2)+
  xlab("")+
  ylab("Standardized Effect\non Centrality")+
  ggtitle("Environmental")+
  coord_flip()+
  theme_classic()+
  scale_color_viridis_c(
    direction = -1, limits = c(0,1.01))+
  theme(
    plot.title = element_text(size = 16, face = "bold"),
    axis.title = element_text(size = 14),
    axis.text = element_text(size = 12),
    legend.title = element_text(size = 13),
    legend.text = element_text(size = 11)
  )


main_fig <- ggarrange(name_plot3, contact_plot3, distance_plot3, enviro_plot3, common.legend = TRUE, labels = c("a", "b", "c", "d"), legend = "right")

ggsave("main_fig_date.pdf", plot = main_fig, width = 12, height = 7)


control_fig <- ggarrange(name_plot4, contact_plot4, distance_plot4, enviro_plot4, common.legend = TRUE, labels = c("a", "b", "c", "d"), legend = "right")

ggsave("control_fig_date.pdf", plot = control_fig, width = 12, height = 7)


```



